name: 'Vib Action'
description: 'Build Vib Image'
author: 'Vanilla OS Team'
branding:
  icon: 'arrow-up'
  color: 'yellow'
inputs:
  recipe:
    description: 'Path to recipe.yml'
    required: true
    default: 'recipe.yml'
  plugins:
    description: 'List of plugins to use'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Vib
      shell: bash
      run: |
        wget https://github.com/Vanilla-OS/Vib/releases/download/v0.3.1/vib
        chmod +x vib

    - name: Run Vib
      shell: bash
      run: |
        ./vib build ${{ inputs.recipe }}
